# Used by build-embedded.sh. No startup code, linker script, or board SDK is
# needed: all compiler probes and project outputs are static libraries/objects.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    ISOTPC_EMBEDDED_TARGET ISOTPC_EMBEDDED_COMPILER ISOTPC_TOOLCHAIN_ROOT ISOTPC_CLANG)

if(ISOTPC_EMBEDDED_TARGET MATCHES "^cortex-m(0|4|7)$")
    set(CMAKE_SYSTEM_PROCESSOR arm)
    set(toolchain_dir "${ISOTPC_TOOLCHAIN_ROOT}/arm")
    set(gcc_triple arm-none-eabi)
    set(clang_triple arm-none-eabi)
    set(cpu_flags "-mcpu=${ISOTPC_EMBEDDED_TARGET} -mthumb")
    if(ISOTPC_EMBEDDED_TARGET STREQUAL "cortex-m0")
        string(APPEND cpu_flags " -mfloat-abi=soft")
    elseif(ISOTPC_EMBEDDED_TARGET STREQUAL "cortex-m4")
        string(APPEND cpu_flags " -mfpu=fpv4-sp-d16 -mfloat-abi=hard")
    else()
        string(APPEND cpu_flags " -mfpu=fpv5-d16 -mfloat-abi=hard")
    endif()
elseif(ISOTPC_EMBEDDED_TARGET MATCHES "^riscv(32|64)$")
    set(CMAKE_SYSTEM_PROCESSOR "${ISOTPC_EMBEDDED_TARGET}")
    set(toolchain_dir "${ISOTPC_TOOLCHAIN_ROOT}/riscv")
    set(gcc_triple riscv-none-elf)
    set(clang_triple "${ISOTPC_EMBEDDED_TARGET}-unknown-elf")
    if(ISOTPC_EMBEDDED_TARGET STREQUAL "riscv32")
        set(cpu_flags "-march=rv32imac -mabi=ilp32")
    else()
        set(cpu_flags "-march=rv64imac -mabi=lp64")
    endif()
elseif(ISOTPC_EMBEDDED_TARGET MATCHES "^esp32(s2|s3)?$")
    set(CMAKE_SYSTEM_PROCESSOR xtensa)
    set(toolchain_dir "${ISOTPC_TOOLCHAIN_ROOT}/esp-xtensa")
    set(gcc_triple "xtensa-${ISOTPC_EMBEDDED_TARGET}-elf")
    set(clang_triple xtensa-esp-elf)
    if(ISOTPC_EMBEDDED_COMPILER STREQUAL "clang")
        set(cpu_flags "-mcpu=${ISOTPC_EMBEDDED_TARGET}")
    else()
        set(cpu_flags "-mlongcalls")
    endif()
elseif(ISOTPC_EMBEDDED_TARGET MATCHES "^esp32c[36]$")
    set(CMAKE_SYSTEM_PROCESSOR riscv32)
    set(toolchain_dir "${ISOTPC_TOOLCHAIN_ROOT}/esp-riscv")
    set(gcc_triple riscv32-esp-elf)
    set(clang_triple riscv32-esp-elf)
    if(ISOTPC_EMBEDDED_TARGET STREQUAL "esp32c3")
        set(cpu_flags "-march=rv32imc_zicsr_zifencei -mabi=ilp32")
    else()
        set(cpu_flags "-march=rv32imac_zicsr_zifencei -mabi=ilp32")
    endif()
else()
    message(FATAL_ERROR "Unsupported embedded target: ${ISOTPC_EMBEDDED_TARGET}")
endif()

set(gcc "${toolchain_dir}/bin/${gcc_triple}-gcc")
if(NOT EXISTS "${gcc}")
    message(FATAL_ERROR "Missing ${gcc}; run install-embedded-toolchain.sh first")
endif()

set(CMAKE_AR "${toolchain_dir}/bin/${gcc_triple}-ar")
set(CMAKE_RANLIB "${toolchain_dir}/bin/${gcc_triple}-ranlib")
set(CMAKE_C_FLAGS_INIT "${cpu_flags} -ffreestanding -ffunction-sections -fdata-sections")

if(ISOTPC_EMBEDDED_COMPILER STREQUAL "gcc")
    set(CMAKE_C_COMPILER "${gcc}")
elseif(ISOTPC_EMBEDDED_COMPILER STREQUAL "clang")
    if(ISOTPC_EMBEDDED_TARGET MATCHES "^esp32")
        set(CMAKE_C_COMPILER "${ISOTPC_TOOLCHAIN_ROOT}/esp-clang/bin/clang")
    else()
        find_program(CMAKE_C_COMPILER NAMES "${ISOTPC_CLANG}")
    endif()
    if(NOT CMAKE_C_COMPILER OR NOT EXISTS "${CMAKE_C_COMPILER}")
        message(FATAL_ERROR "Clang not found; install clang or esp-clang for this target")
    endif()
    set(CMAKE_C_COMPILER_TARGET "${clang_triple}")
    # Use the same target libc headers as GCC. Do not use host headers or GCC's
    # compiler-internal include directory (Clang supplies its own builtins).
    execute_process(COMMAND "${gcc}" -print-sysroot
        OUTPUT_VARIABLE target_sysroot OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE sysroot_status)
    if(NOT sysroot_status EQUAL 0 OR NOT EXISTS "${target_sysroot}/include/stdio.h")
        message(FATAL_ERROR "Cannot locate the target libc headers using ${gcc} -print-sysroot")
    endif()
    set(CMAKE_SYSROOT "${target_sysroot}")
    string(APPEND CMAKE_C_FLAGS_INIT " -isystem \"${target_sysroot}/include\"")
else()
    message(FATAL_ERROR "Unsupported compiler: ${ISOTPC_EMBEDDED_COMPILER}")
endif()

set(CMAKE_FIND_ROOT_PATH "${toolchain_dir}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
