name: Windows MSVC Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  COVERAGE_MIN: 80

jobs:
  build_standard:
    name: Build with MSVC via CMake
    runs-on: windows-2022

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -S . -B build  -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -Disotpc_ENABLE_TESTING=ON

      - name: Check library.json
        run: cmake --build build --target check-library-json --config Release

      - name: Build (Release)
        run: cmake --build build --config Release -- /m

      - name: Run unit tests
        if: always()
        run: |
          cd build
          ctest --output-on-failure --timeout 120
  
  build_w_custom_can_arg:
    name: Build with MSVC via CMake; enabled user-CAN-arg
    runs-on: windows-2022

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -S . -B build  -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -Disotpc_ENABLE_CAN_SEND_ARG=ON -Disotpc_ENABLE_TESTING=ON

      - name: Check library.json
        run: cmake --build build --target check-library-json --config Release

      - name: Build (Release)
        run: cmake --build build --config Release -- /m

      - name: Run unit tests
        if: always()
        run: |
          cd build
          ctest --output-on-failure --timeout 120

  
  build_standard_w_events:
    name: Build with MSVC via CMake
    runs-on: windows-2022

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -S . -B build  -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -Disotpc_ENABLE_TRANSCEIVE_EVENTS=ON -Disotpc_ENABLE_TESTING=ON

      - name: Check library.json
        run: cmake --build build --target check-library-json --config Release

      - name: Build (Release)
        run: cmake --build build --config Release -- /m

      - name: Run unit tests
        if: always()
        run: |
          cd build
          ctest --output-on-failure --timeout 120

  
  
  build_w_custom_can_arg_w_events:
    name: Build with MSVC via CMake; enabled user-CAN-arg
    runs-on: windows-2022

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -S . -B build  -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -Disotpc_ENABLE_CAN_SEND_ARG=ON  -Disotpc_ENABLE_TRANSCEIVE_EVENTS=ON -Disotpc_ENABLE_TESTING=ON

      - name: Check library.json
        run: cmake --build build --target check-library-json --config Release

      - name: Build (Release)
        run: cmake --build build --config Release -- /m

      - name: Run unit tests
        if: always()
        run: |
          cd build
          ctest --output-on-failure --timeout 120

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Submodules
      run: git submodule update --init --recursive

    - name: Install gcovr
      run: python -m pip install --upgrade pip gcovr

    - name: Configure CMake (coverage)
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=Debug \
          -Disotpc_ENABLE_TESTING=ON \
          -Disotpc_ENABLE_COVERAGE=ON \
          -Disotpc_COVERAGE_MIN=${{env.COVERAGE_MIN}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Coverage
      run: cmake --build ${{github.workspace}}/build --target coverage

