name: Build with classic Makefile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout Submodules
      run: git submodule update --init --recursive

    - name: Run Makefile
      run: make all

    # Check if bin directory was created
    - name: Check build
      run: |
        if [ ! -d "bin" ]; then
          echo "Build failed: bin directory not found"
          exit 1
        fi

        if [ ! -l "bin/libisotp.so" ]; then
          echo "Build failed: libisotp.so not found"
          exit 2
        fi

